resources:
  - ../nerc-shift-1

patches:
  # Use the letsencrypt staging issuer
  # - path: patches/ingress-cert-manager-staging.yaml
  #   target:
  #     kind: Ingress
  #     name: keycloak
  # Rename the host to keycloakdev.mss.mghpcc.org
  - path: patches/ingress-host-keycloakdev.yaml
    target:
      kind: Ingress
      name: keycloak
  - path: patches/realm-authurl.json
    target:
      kind: KeycloakRealm
      name: mss

patchesStrategicMerge:
  - patches/clients-regapp.yaml
  - patches/clients-coldfront.yaml
  - patches/idp-cilogon.yaml
  - patches/ha-postgres.yaml
