apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: mss-keycloak
  namespace: keycloak
  labels:
    app: mss-keycloak
spec:
  instances: 1
  keycloakDeploymentSpec:
    experimental:
      env:
        - name: CILOGON_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: CLIENT_ID
              name: keycloak-cilogon-idp-secret
        - name: CILOGON_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: CLIENT_SECRET
              name: keycloak-cilogon-idp-secret
        - name: DB_ADDR
          valueFrom:
            secretKeyRef:
              name: mss-keycloak-pgha-pguser-mss-keycloak-pgha
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: mss-keycloak-pgha-pguser-mss-keycloak-pgha
              key: port
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mss-keycloak-pgha-pguser-mss-keycloak-pgha
              key: dbname
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mss-keycloak-pgha-pguser-mss-keycloak-pgha
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mss-keycloak-pgha-pguser-mss-keycloak-pgha
              key: password
      volumes:
        defaultMode: 0777
        items:
          # - name: cilogon-idp-secret
          #   secrets:
          #     - keycloak-cilogon-idp-secret
          #   # $JBOSS_HOME/secrets - supported by kc container
          #   # reference in keycloak as ${vault.cilogon_client_secret}
          #   mountPath: /opt/jboss/keycloak/secrets
          #   items:
          #     - key: CLIENT_SECRET
          #       path: mss_cilogon__client__secret
          - name: nerc-setup
            configMaps:
              - nerc-setup
            mountPath: /opt/jboss/startup-scripts
            items:
              - key: nerc-setup.sh
                path: nerc-setup.sh
                mode: 0777
  externalDatabase:
    enabled: true
  externalAccess:
    enabled: true
