namespace: keycloak
resources:
  - secrets/pgo-s3-conf.yaml
  - ha-postgres.yaml
  - ../../base
  - keycloakrealm.yaml
  - regapp-client.yaml
  - secrets/keycloak-tls.yaml
  - keycloak-idp-cilogon.yaml
  - ingress.yaml

patchesStrategicMerge:
  - patches/keycloak.yaml

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
  - name: regapp-client-script
    files:
    - regapp-client-script.sh
