apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: mss-keycloak
  namespace: keycloak
spec:
  externalAccess:
    enabled: true
  extensions:
    - >-
      https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar
  instances: 1
